name: Scheduled Function Call

on:
  schedule:
    - cron: '0 0 * * *'  # This will run every day at midnight UTC

jobs:
  call-vercel-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel endpoint
        run: curl -X GET "https://your-vercel-deployment.vercel.app/api/update"
