name: Update Anime Data

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 noon UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    env:
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to latest version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Run update script
        run: |
          pipenv run python update.py
