name: Scheduled Anime Scraper

on:
  schedule:
    # This cron syntax will run the job every day at 12:00 PM UTC
    - cron: "0 12 * * *"

jobs:
  scrape_anime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you have a different dependency file

      - name: Run the scraper
        run: |
          python your_script_name.py  # Replace with your actual script name
