name: Update Anime Data

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 noon UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    env:
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pyenv and Python
        run: |
          # Install pyenv
          curl https://pyenv.run | bash
          
          # Add pyenv to PATH
          export PATH="/home/runner/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"

          # Install Python 3.12 using pyenv
          pyenv install 3.12.0

          # Set Python 3.12 as global (optional)
          pyenv global 3.12.0

      - name: Verify Python version
        run: |
          python --version

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv --rm  # Remove existing virtual environment
          pipenv install --deploy --ignore-pipfile

      - name: Run update script
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pipenv run python update.py
